bpftool-native: Fix -Wdiscarded-qualifiers errors for glibc 2.42+
Backport a patch from kernel to fix the following build errors.

bbpf.c: In function ‘kallsyms_cb’:
| libbpf.c:8192:13: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
|  8192 |         res = strstr(sym_name, ".llvm.");
|       |             ^
| libbpf.c: In function ‘avail_kallsyms_cb’:
| libbpf.c:11497:31: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
| 11497 |                 if (!(sym_sfx = strstr(sym_name, ".llvm.")))
|       |                               ^
| libbpf.c: In function ‘resolve_full_path’:
| libbpf.c:12085:35: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
| 12085 |                         next_path = strchr(s, ':');
|       |

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>
(cherry picked from commit 0a3798eaed3f45a93463414c0f4752b54e8978de)
Signed-off-by: Anuj Mittal <anuj.mittal@oss.qualcomm.com>