pcsc-lite: use nonarch_libdir for sysusers.d
It uses pkg-config to query systemd's sysusersdir which is defined as:

sysusers_dir=${prefix}/lib/sysusers.d
sysusersdir=${sysusers_dir}

Fixes installed-vs-shipped in cases where libdir isn't 'lib':

ERROR: QA Issue: pcsc-lite: Files/directories were installed but not shipped in any package:
  /usr/lib/sysusers.d
  /usr/lib/sysusers.d/pcscd-sysusers.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
pcsc-lite: 2 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>